name = "tna-client"
author = "Phargot&Furuwashi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14217a4eba2e8413ebf5a3793a6a921868bb535fc8178c42e73d09623ce406df"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
