name = "tna-client"
author = "Phargot&Furuwashi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "99fbf3beabc242f6175b35097888dd356bb6b6da80ce8ff248eb9616ad74e495"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
