name = "tna-client"
author = "Phargot&Furuwashi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f341afef1267afe75eeaca774da68ecf6a6e4a47bbfb6e83f4f367641d99032"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
