name = "tna-client"
author = "Phargot&Furuwashi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eae83406a6d55ec3d1532042d01853fd5b90d8cbf3c068b8f6a5fdcc7c70f16f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
