name = "tna-client"
author = "Phargot&Furuwashi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e858f7ccfa8c9c2aac58f7f91ebab2b5609d117a12444a8b1b022ba1700c40e4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
