name = "tna-client"
author = "Phargot&Furuwashi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2fbb30bcf601f152c587eb2f6722661995e7fd878a2f4060d460cd63c6dbcc79"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
