name = "tna-modpack-server"
author = "Phargot&Furuwashi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a818066c05a2e0b129c90f4b53d0eff0aca7b3f705fd4669787a0c4db586f8cf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
