name = "tna-modpack-server"
author = "Phargot&Furuwashi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bff25028c0605243435e731a9bc5405b8b985438c323b07251be88e6b3301216"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
